Repository nickBes/shithead, pull requests merged in 2022-01, with the labels that each got.

#4 added a basic websocket server with some basic websocket communication
  shithead_game_server/.gitignore
  shithead_game_server/Cargo.lock
  shithead_game_server/Cargo.toml
  shithead_game_server/design_prototype.rs
  shithead_game_server/src/main.rs
Labels: back

#6 the server now receives json messages from the clients and broadcasts them
  shithead_game_server/Cargo.lock
  shithead_game_server/Cargo.toml
  shithead_game_server/src/client_handler.rs
  shithead_game_server/src/game_server.rs
  shithead_game_server/src/main.rs
  shithead_game_server/src/messages.rs
Labels: back

#7 The server and client now perform a handshake once connected, and communicate card clicks
  shithead_game_server/src/client_handler.rs
  shithead_game_server/src/game_server.rs
  shithead_game_server/src/messages.rs
Labels: back

#8 created a next project after realizing (5 hours) that it's the only o…
  webapp/.eslintrc.json
  webapp/.gitignore
  webapp/README.md
  webapp/next-env.d.ts
  webapp/next.config.js
  webapp/package-lock.json
  webapp/package.json
  webapp/pages/_app.tsx
  webapp/pages/api/hello.ts
  webapp/pages/index.tsx
  webapp/public/favicon.ico
  webapp/public/vercel.svg
  webapp/styles/Home.module.scss
  webapp/styles/globals.scss
  webapp/tsconfig.json
Labels: enhancement, front

#13 The game server now supports lobbies
  shithead_game_server/Cargo.lock
  shithead_game_server/Cargo.toml
  shithead_game_server/design_prototype.rs
  shithead_game_server/src/card.rs
  shithead_game_server/src/client_handler.rs
  shithead_game_server/src/game_server.rs
  shithead_game_server/src/lobby.rs
  shithead_game_server/src/main.rs
  shithead_game_server/src/messages.rs
Labels: back

#16 the client can now ask the server for a list of lobbies to refresh it
  shithead_game_server/src/client_handler.rs
  shithead_game_server/src/messages.rs
Labels: back

#17 Now sending lobby updates to clients in the lobby
  shithead_game_server/src/client_handler.rs
  shithead_game_server/src/game_server.rs
  shithead_game_server/src/lobby.rs
  shithead_game_server/src/messages.rs
Labels: back

#25 implemented the card struct and the deck initialization process
  shithead_game_server/Cargo.lock
  shithead_game_server/Cargo.toml
  shithead_game_server/src/card.rs
  shithead_game_server/src/client_handler.rs
  shithead_game_server/src/lobby.rs
Labels: back

#26 now using ts-rs to generate typescript bindings for rust structs
  shithead_game_server/Cargo.lock
  shithead_game_server/Cargo.toml
  shithead_game_server/bindings/ClickedCardLocation.ts
  shithead_game_server/bindings/ClientMessage.ts
  shithead_game_server/bindings/ExposedLobbyInfo.ts
  shithead_game_server/bindings/ExposedLobbyPlayerInfo.ts
  shithead_game_server/bindings/ServerMessage.ts
  shithead_game_server/src/game_server.rs
  shithead_game_server/src/messages.rs
Labels: enhancement, front, back

#28 the client now start the game if he is the owner
  shithead_game_server/Cargo.lock
  shithead_game_server/Cargo.toml
  shithead_game_server/src/client_handler.rs
  shithead_game_server/src/game_server.rs
  shithead_game_server/src/lobby.rs
  shithead_game_server/src/messages.rs
Labels: back

#29 the message enums are now tagged for easier usage in typescript code
  shithead_game_server/bindings/ClientMessage.ts
  shithead_game_server/bindings/ServerMessage.ts
  shithead_game_server/src/client_handler.rs
  shithead_game_server/src/game_server.rs
  shithead_game_server/src/lobby.rs
  shithead_game_server/src/messages.rs
Labels: front, back

#31 the server can now send messages to specific clients outside of their handler
  shithead_game_server/src/client_handler.rs
  shithead_game_server/src/game_server.rs
Labels: back

#33 improved the ts bindings so that we can use ts pattern matching to run code for each message
  shithead_game_server/Cargo.lock
  shithead_game_server/Cargo.toml
  shithead_game_server/bindings/ClickedCardLocation.ts
  shithead_game_server/bindings/ClientMessage.ts
  shithead_game_server/bindings/ExposedLobbyInfo.ts
  shithead_game_server/bindings/ExposedLobbyPlayerInfo.ts
  shithead_game_server/bindings/ServerMessage.ts
  shithead_game_server/bindings/bindings.ts
  shithead_game_server/src/client_handler.rs
  shithead_game_server/src/game_server.rs
  shithead_game_server/src/lobby.rs
  shithead_game_server/src/messages.rs
Labels: front, back

#35 now updating players about their initial cards when the game starts
  shithead_game_server/src/card.rs
  shithead_game_server/src/game_server.rs
  shithead_game_server/src/lobby.rs
  shithead_game_server/src/messages.rs
Labels: back

#39 created a gui to view and search lobbies
  webapp/client/messages.ts
  webapp/components/Lobbies/lobbies.module.scss
  webapp/components/Lobbies/lobbies.tsx
  webapp/components/Lobbies/lobby.tsx
  webapp/components/Lobbies/not_found.tsx
  webapp/package-lock.json
  webapp/package.json
  webapp/pages/_app.tsx
  webapp/pages/api/hello.ts
  webapp/pages/index.tsx
  webapp/styles/Home.module.scss
  webapp/styles/_theme.scss
  webapp/styles/globals.scss
  webapp/styles/index.module.scss
  webapp/tsconfig.json
Labels: enhancement, front

#53 the server now responds to ping messages
  shithead_game_server/src/client_handler.rs
Labels: bug, back

#50 added server side turn management
  shithead_game_server/bindings/bindings.ts
  shithead_game_server/src/cards/cards_by_id_cache.rs
  shithead_game_server/src/cards/deck.rs
  shithead_game_server/src/cards/mod.rs
  shithead_game_server/src/client_handler.rs
  shithead_game_server/src/game_server.rs
  shithead_game_server/src/lobby/lobby_player.rs
  shithead_game_server/src/lobby/mod.rs
  shithead_game_server/src/lobby/ordered_lobby_players.rs
  shithead_game_server/src/lobby/turn.rs
  shithead_game_server/src/main.rs
  shithead_game_server/src/messages.rs
Labels: back
