Repository nickBes/shithead, pull requests merged in 2022-06, with the labels that each got.

#62 migration from react into vue
  client/.gitignore
  client/env.d.ts
  client/index.html
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/src/App.vue
  client/src/game/socket.ts
  client/src/game/states.ts
  client/src/main.ts
  client/src/router/index.ts
  client/src/views/Home.vue
  client/src/views/Lobby.vue
  client/src/views/LobbyCreator.vue
  client/tsconfig.json
  client/tsconfig.vite-config.json
  client/vite.config.ts
Labels: front

#68 now can join lobby through lobby list
  client/src/game/states.ts
  client/src/views/Home.vue
  client/src/views/Lobby.vue
  client/src/views/LobbyCreator.vue
Labels: front

#72 now not sending lobbies during handshake
  shithead_game_server/bindings/bindings.ts
  shithead_game_server/src/client_handler.rs
  shithead_game_server/src/test_client.rs
Labels: enhancement, back

#66 can now only start game if lobby has at least 2 players
  shithead_game_server/src/game_server.rs
Labels: bug

#71 fixed the deadlock in the cleanup routine
  shithead_game_server/src/game_server.rs
Labels: bug

#75 leaving lobby when switching route
  client/src/views/Lobby.vue
Labels: front

#77 now properly setting a player's lobby id to None after leaving a lobby
  shithead_game_server/src/client_handler.rs
Labels: bug, back

#78 now user can set his name
  client/src/App.vue
  client/src/game/states.ts
  client/src/views/Home.vue
Labels: front

#80 Feature.send username during handshake
  client/src/App.vue
  client/src/main.ts
  shithead_game_server/bindings/bindings.ts
  shithead_game_server/src/cards/cards_by_id_cache.rs
  shithead_game_server/src/cards/deck.rs
  shithead_game_server/src/client_handler.rs
  shithead_game_server/src/game_server.rs
  shithead_game_server/src/lobby/lobby_player.rs
  shithead_game_server/src/lobby/mod.rs
  shithead_game_server/src/messages.rs
  shithead_game_server/src/test_client.rs
  shithead_game_server/tests/perform_handshake.rs
  shithead_game_server/tests/util/mod.rs
Labels: enhancement, front, back

#70 implemented clicking the trash
  shithead_game_server/src/cards/deck.rs
  shithead_game_server/src/cards/mod.rs
  shithead_game_server/src/client_handler.rs
  shithead_game_server/src/game_server.rs
  shithead_game_server/src/lobby/lobby_player.rs
  shithead_game_server/src/lobby/mod.rs
  shithead_game_server/src/lobby/ordered_lobby_players.rs
  shithead_game_server/src/messages.rs
Labels: back

#81 now can add error messages andhave an handler for on message callbacks
  client/src/App.vue
  client/src/game/socket.ts
  client/src/game/states.ts
  client/src/views/Home.vue
  client/src/views/Lobby.vue
  client/src/views/LobbyCreator.vue
Labels: front

#90 fixed bug when player left during his turn
  shithead_game_server/bindings/bindings.ts
  shithead_game_server/src/client_handler.rs
  shithead_game_server/src/game_server.rs
  shithead_game_server/src/lobby/mod.rs
Labels: bug, back

#91 the user is now only allowed to change his username outside of a lobby
  shithead_game_server/src/client_handler.rs
  shithead_game_server/src/game_server.rs
Labels: bug, back

#95 Feature.send players on join lobby
  client/src/views/Lobby.vue
  client/src/views/LobbyCreator.vue
  shithead_game_server/bindings/bindings.ts
  shithead_game_server/src/client_handler.rs
  shithead_game_server/src/game_server.rs
  shithead_game_server/src/lobby/mod.rs
  shithead_game_server/src/lobby/ordered_lobby_players.rs
  shithead_game_server/src/messages.rs
  shithead_game_server/tests/create_join_lobby.rs
Labels: front, back

#99 added server logging
  shithead_game_server/src/client_handler.rs
  shithead_game_server/src/lobby/mod.rs
Labels: enhancement, back

#101 now have autocompletion for lobbies using naive ui components
  client/package-lock.json
  client/package.json
  client/src/App.vue
  client/src/views/Home.vue
Labels: enhancement, front

#102 Feature.select top 3
  shithead_game_server/bindings/bindings.ts
  shithead_game_server/src/cards/deck.rs
  shithead_game_server/src/client_handler.rs
  shithead_game_server/src/game_server.rs
  shithead_game_server/src/lib.rs
  shithead_game_server/src/lobby/in_game.rs
  shithead_game_server/src/lobby/lobby_player.rs
  shithead_game_server/src/lobby/mod.rs
  shithead_game_server/src/lobby/turn.rs
  shithead_game_server/src/main.rs
  shithead_game_server/src/messages.rs
  shithead_game_server/src/util.rs
Labels: back

#107 now only sending lobbies that are in the waiting state in the get lobbies msg
  shithead_game_server/src/game_server.rs
Labels: enhancement, back

#106 Feature.three up selection updates
  shithead_game_server/src/game_server.rs
  shithead_game_server/src/lobby/in_game.rs
  shithead_game_server/src/lobby/mod.rs
  shithead_game_server/src/lobby/ordered_lobby_players.rs
  shithead_game_server/src/messages.rs
Labels: back
